# Generated by Django 4.1.5 on 2023-05-18 12:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Main.fulluser",),
            managers=[
                ("staff", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="fulluser",
            name="role",
            field=models.CharField(
                choices=[("STAFF", "STAFF")], default="", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dataform",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="StaffProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
