# Generated by Django 4.1.5 on 2023-07-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttestationDepot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.IntegerField(default=0, null=True)),
                ("cheque", models.CharField(max_length=150, null=True)),
                ("date", models.DateField(auto_now_add=True, null=True)),
                (
                    "detenteur",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Main.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttestationPaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.IntegerField(default=0, null=True)),
                ("banque", models.CharField(max_length=150, null=True)),
                ("date", models.DateField(auto_now_add=True, null=True)),
                (
                    "detenteur",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Main.client",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Attestation",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "ADMIN"), ("2", "STAFF")], default="2", max_length=20
            ),
        ),
    ]
